"""Initial migration for PostgreSQL

Revision ID: aba64d74ec58
Revises: 
Create Date: 2025-09-17 10:41:11.421091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba64d74ec58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'images',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'DONE', 'ERROR',
                  name='imagestatus'), nullable=False),
        sa.Column('original_url', sa.String(), nullable=False),
        sa.Column('thumbnails', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
